# Generated by Django 5.2.3 on 2025-06-23 03:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de Compra')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('quantity_purchased', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Comprada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas de Compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='inventory.inventoryitem', verbose_name='Ítem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='inventory.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Registro de Compra',
                'verbose_name_plural': 'Registros de Compra',
                'ordering': ['-purchase_date', 'item__name'],
            },
        ),
    ]
